src/Entity/Improve.php
<?php

namespace App\Entity;

use App\Repository\ImproveRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\HasLifecycleCallbacks;

#[ORM\Entity(repositoryClass: ImproveRepository::class), HasLifecycleCallbacks]
class Improve implements  TimestampableInterface
{
    use TimestampableTrait;
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 1000)]
    private ?string $Title = null;

    /**
     * @var Collection<int, Fail>
     */
    #[ORM\OneToMany(targetEntity: Fail::class, mappedBy: 'improve')]
    #[ORM\OrderBy(['createdAt' => 'ASC'])]
    private Collection $fails;

    #[ORM\Column]
    private ?bool $onlyWorkingDays = null;

    #[ORM\ManyToOne(inversedBy: 'improves')]
    private ?ImproveGroup $improveGroup = null;

    public function __construct()
    {
        $this->fails = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): static
    {
        $this->Title = $Title;

        return $this;
    }

    /**
     * @return Collection<int, Fail>
     */
    public function getFails(): Collection
    {
        return $this->fails;
    }

    public function addFail(Fail $fail): static
    {
        if (!$this->fails->contains($fail)) {
            $this->fails->add($fail);
            $fail->setImprove($this);
        }

        return $this;
    }

    public function removeFail(Fail $fail): static
    {
        if ($this->fails->removeElement($fail)) {
            // set the owning side to null (unless already changed)
            if ($fail->getImprove() === $this) {
                $fail->setImprove(null);
            }
        }

        return $this;
    }

    public function isOnlyWorkingDays(): ?bool
    {
        return $this->onlyWorkingDays;
    }

    public function setOnlyWorkingDays(bool $onlyWorkingDays): static
    {
        $this->onlyWorkingDays = $onlyWorkingDays;

        return $this;
    }

    public function getImproveGroup(): ?ImproveGroup
    {
        return $this->improveGroup;
    }

    public function setImproveGroup(?ImproveGroup $improveGroup): static
    {
        $this->improveGroup = $improveGroup;

        return $this;
    }
}

templates/app/edit_fail.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container-fluid">
        <h1>Upravit Fail</h1>

        <div class="pt-5">
            {{ form_start(form) }}
            {{ form_row(form.createdAt) }}
            <div class="d-flex">
                {{ form_row(form.submit) }}
                <a class="btn btn-warning mb-3 ms-1" href="{{ path('upsert_improve', {'improve_id': improve.id}) }}">Späť</a>
            </div>
            {{ form_end(form) }}
        </div>

    </div>
{% endblock %}

templates/app/index.html.twig
{% extends 'base.html.twig' %}


{% block body %}

    <div class="container-fluid">
        <div class="d-flex justify-content-between align-items-center">
            <h1>Ako byť lepší...</h1>
        </div>
        <div class="d-flex mb-3">
        <a href="{{ path('upsert_improve_group') }}" class="btn btn-outline-secondary ">Pridať novú skupinu</a>
        <a href="{{ path('upsert_improve') }}" class="btn btn-outline-primary ms-2">Pridaj Zlepšenie</a>
        </div>
        {% for improveGroup in improveGroups %}
            <div class="d-flex justify-content-between align-items-center">
                {% set tpi = improveGroup.totalPercentageImprove %}
                <h2>{{ improveGroup.title }}</h2>
                <strong class="fs-3 {% if tpi >= 90 %}text-success{% elseif tpi < 90 and tpi > 70 %}text-warning{% else %}text-danger{% endif %}">{{ tpi }}
                    %</strong>
            </div>
            <table class="pt-5 table table-bordered">
                {% if improveGroup.improves | length %}
                    {% for improve in improveGroup.improves %}
                        {% set lastFail = improve.fails | last %}
                        <tr class="d-flex align-items-center">
                            <td class="bg-transparent w-50 border-0">
                                <strong>{{ improve.title }}</strong><br>
                                Začiatok: {{ improve.createdAt | date('d.M.Y') }}
                            </td>
                            <td class="bg-transparent w-50 border-0">
                                Celkovo dní: {{ improve.total_improve_days }}<br>
                                Počet zlyhaní: {{ improve.total_bad_days }}<br>
                                Úspešnosť: {{ improve.percentage_improve_days }}%<br>
                                Najdlhšia séria dní: {{ improve.max_days_in_one_line }}<br>
                                Aktuálna séria dní: {{ improve.actual_days_in_one_line }}<br>
                                Posledné zlyhanie: {{ lastFail ? lastFail.createdAt | date('d.M.Y'): '-' }}<br>
                            </td>
                            <td class="bg-transparent d-flex w-25 justify-content-end border-0">
                                <a href="{{ path('upsert_improve', {'improve_id': improve.id}) }}"
                                   class="btn btn-sm btn-outline-primary d-flex align-items-center">Edit</a>
                                <a href="{{ path('add_fail', {'improve_id': improve.id}) }}"
                                   class="btn btn-sm btn-outline-danger ms-2 d-flex align-items-center">Zlyhal som</a>
                            </td>
                        </tr>
                    {% endfor %}
                {% endif %}
            </table>
        {% endfor %}


    </div>
{% endblock %}

templates/app/upsert_improve.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container-fluid">
        <h1>Čo chcem zlepšiť</h1>

        <div class="pt-5">
            {{ form_start(form) }}
            {{ form_row(form.title) }}
            {{ form_row(form.improveGroup) }}
            {{ form_row(form.createdAt) }}
            {{ form_row(form.onlyWorkingDays) }}
            <div class="d-flex">
                {{ form_row(form.submit) }}
                <a class="btn btn-warning mb-3 ms-1" href="{{ path('index') }}">Späť</a>
            </div>
            {{ form_end(form) }}
        </div>
        <table class="pt-5 table table-bordered">
            {% for fail in improve.fails %}
                <tr class="d-flex align-items-center">
                    <td class="bg-transparent w-100 border-0">{{ fail.createdAt | date('d.M.Y') }}</td>
                    <td class="bg-transparent d-flex justify-content-end border-0">
                        <a href="{{ path('edit_fail', {'fail_id' : fail.id}) }}" class="btn btn-sm btn-outline-primary ms-2">Edit</a>
                        <a href="{{ path('remove_fail', {'improve_id': fail.improve.id, 'fail_id' : fail.id}) }}" class="btn btn-sm btn-outline-danger ms-2">Zmazať</a>
                    </td>
                </tr>
            {% endfor %}
        </table>

    </div>
{% endblock %}

templates/app/upsert_improve_group.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container-fluid">
        <h1>Čo chcem zlepšiť</h1>

        <div class="pt-5">
            {{ form_start(form) }}
            {{ form_row(form.title) }}
            <div class="d-flex">
                {{ form_row(form.submit) }}
                <a class="btn btn-warning mb-3 ms-1" href="{{ path('index') }}">Späť</a>
            </div>
            {{ form_end(form) }}
        </div>

    </div>
{% endblock %}